### ISSUE TITLE
Errors with WT_mini

### ISSUE THREAD

**Issue by olawa** [fairliereese/LR-splitpipe#10]
Hi,
I am trying LR-splitpipe for a Parse WT_mini kit sequenced with nanopore. The v2.0 release worked, but identified very few matches for bc1, otherwise everything works so it is not obvious what the issue is. It looks like this and other things have been fixed now so perhaps it would be good with a new release soon :)

I encountered a few bugs when running the latest code, the argument parsing only works if --chunksize is present and is given as a string and likewise --max_read_len needs to be defined if it is not in the argument list.

Also for WT_mini the number of wells used ar 12 so it needs to be changed from 28 in utils.py here:
def get_bc_round_set(kit):
	KIT_INT_DICT = {'custom_1': 1, 'WT': 48, 'WT_mini': 28, 'WT_mega': 96}
	kit_n = KIT_INT_DICT[kit]
	if kit_n == 12:
		bc_round_set = [['bc1','n24_v4'], ['bc2','v1'], ['bc3','v1']]

Thanks for making this available, with these changes everything seems to work fine with a good % reads classified.

**Comment by fairliereese** [comment]
Hi there! I appreciate the detailed list of bugs. If you've already solved them on your side though, maybe you could submit a pull request? 

I'd also be interested in helping debug the low match rate for bc1, if you could provide me with more details on that (ie the QC plots and / or numbers) that would be helpful!
