### ISSUE TITLE
Question regarding reads being filtered out due to invalid linker combinations

### ISSUE THREAD

**Issue by catsargent** [fairliereese/LR-splitpipe#12]
Hi, 

Sorry, this is actually a question, not an issue. I ran LR-splitpipe on our data (single cell splitseq library sent for amplicon sequencing by PacBio). LR-splitpipe ran through no problem and I have also run the data through Talon but the data are really sparse and I am not sure why. We have the SR sc-splitseq data from the same library and the data look fine there. 

One thing I noticed was that we start with 3.7 million reads. After running LR-splitpipe there are only 1.7M reads. I took a look at the log file created when running LR-splitpipe and found the following lines, which indicates that 2M reads were filtered out due to having invalid linker combinations:
```
Found linkers for 3800000 reads
Found 1769691 reads with valid linker combinations
```

Is it normal for so many reads to be filtered out in this step? 

Also, is there any documentation for interpreting the figures that are produced when running LR-splitpipe? For instance, I am not sure how to interpret the figures relating to linkers. 

Additionally, I think that the figure showing the cells ranked by number of UMIs (see attached plot) has the legends swapped  i.e. the x axis shows the # UMIs in log scale and the y axis ranked cells by number of UMIs. You can see in this plot that most cells have very few UMIs (which is not the case in the SR-sc data). The cells here have been filtered to the set of barcodes that passed QC filtering in the short read dataset so it's very strange (additionally there were 10000 cells that passed filtering in the SR sc dataset).

![LR_post_correction_knee_plot](https://user-images.githubusercontent.com/38214629/212291453-c598115f-5dd4-4898-9824-e6f10cd96ada.png)
 
Thanks,
Catherine

**Comment by fairliereese** [comment]
In my experience, it's absolutely normal to see such a dramatic drop in valid reads. For reads to pass this filtering step they must contain both linkers 1 and 2 in the same strandedness below a certain mismatch threshold. And in the cases where you use the maximum read length (max_read_len) and maximum distance (max_linker_dist) flags, they must be in a read <max_read_len and must be within the last (or first) max_linker_dist bp of the read. With all these criteria there tends to be a pretty substantial drop in valid reads.

 Currently there is no documentation for the plots that are generated but I will try to write some in the near future.

The labels on the plots are not switched but the "logscale" part of the ylabel is definitely wrong as you mentioned and I will also fix this in a future update.

**Comment by yxsee** [comment]
Hi @fairliereese and @catsargent, sorry to hijack this thread. I was wondering if you see a lot of TSO artifacts among the invalid reads, similar to that detected in Iso-seq? (Image from https://www.pacb.com/wp-content/uploads/Single-Cell-Iso-Seq-Library-Preparation-Using-SMRTbell-Express-Template-Prep-Kit-2.0-Customer-Training.pdf, slides 31 and 32)
![image](https://user-images.githubusercontent.com/47131071/215381135-54501372-a30e-4268-891a-ab27566ca5ef.png)
