### ISSUE TITLE
Question: Why is the order of barcodes 1 and 3 swapped after running modified_add_bam_tag.py?

### ISSUE THREAD

**Issue by catsargent** [fairliereese/LR-splitpipe#13]
Hi,

Sorry for the multiple posts but I am trying to pinpoint whether there is an issue with our data or at some point in our workflow.

Why when adding the barcode sequences as a bam tag are barcodes 1 and 3 swapped?

in get_read_info	
```
        bc_umi = read_bc[1]
	bc_umi = bc_umi.split('_')
	bc = ''.join(bc_umi[0:-1][::-1])
	umi =  bc_umi[-1]
```
and then in main:
```
				bc3 = bc[:8]
				bc2 = bc[8:16]
				bc1 = bc[16:]
				if bc1 in bc_df.bc1_randhex.tolist():
					bc1 = bc_df.loc[bc_df.bc1_randhex==bc1, 'bc1_dt'].values[0]
					bc = bc3+bc2+bc1
```

The reason why this matters to me is because prior to doing the mapping with Minimap2, my fastq file contained human and chimpanzee reads. Additionally, we have SR-splitseq data that I ran through parse biosciences splitseq pipepline. Therefore I filtered our fastq files for 
1. barcodes that were in the filtered set of cells after running parse biosciences' pipeline
2. chimp / human barcodes, producing separate fastq files. 

I therefore wondered what the logic is for later swapping the sequence order of barcodes 1 and 3  to make sure that I am not somehow filtering incorrectly.

Thanks,
Catherine

**Comment by fairliereese** [comment]
I know this is not a great answer but don't worry about the barcode code. I did not do a great job being consistent throughout the pipeline regarding how I named each barcode, but I am confident that the output barcodes are correct based on checks such as matching the barcode combinations to corresponding short-read barcodes (which is what you mentioned above), counting the number of unique barcodes per position (in my case with the original kit it was 48 for bc1 and 96 for bc2 and 3), and matching the barcodes to valid barcodes as recorded by Parse in each position. It was definitely worth checking out but this is something I've definitely vetted!
