### ISSUE TITLE
Generating sam file after demultiplex.py?

### ISSUE THREAD

**Issue by kwglam** [fairliereese/LR-splitpipe#16]
I would like to run add_bam_tag.py after running demultiplex.py. I have got a _demux.fastq file but no sam files after running demultiplex.py. Are we supposed to use sam files as inputs for add_bam_tag.py? Thanks!

**Comment by fairliereese** [comment]
Hi there, you're going to want to map your `*_demux.fastq` file before running `add_bam_tag.py`!

**Comment by kwglam** [comment]
Thanks!
I ran minimap2 with the following code:

minimap2 -ax splice -uf --sam-hit-only -t 20 --junc-bed junctions.bed GRCh38.primary_assembly.genome.fa.gz _demux.fastq --MD > LRdemux_minimap2.sam

After getting the sam file, I ran add_bam_tag.py with this:

python /home/packages/LR-splitpipe/LR-splitpipe/add_bam_tag.py -s LRdemux_minimap2.sam -k WT_mini --merge_primers -o /home/LR-splitpipe_outputs

However, I got the following error:

Traceback (most recent call last):
  File "/home/packages/LR-splitpipe/LR-splitpipe/add_bam_tag.py", line 186, in <module>
    if __name__ == '__main__': main()
  File "/home/packages/LR-splitpipe/LR-splitpipe/add_bam_tag.py", line 109, in main
    df[['read_name', 'bc_umi']] = df['raw_read_name'].str.split(':', expand=True)
  File "/home/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3160, in __setitem__
    self._setitem_array(key, value)
  File "/home/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3189, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key

Do you think it was caused by the options I used for minimap? Any insights? Thanks!!

**Comment by fairliereese** [comment]
My best guess is that for some reason you have read names in your FASTQ that the `add_bam_tag.py` utility can't parse correctly. Would you be able to `head` your demultiplexed FASTQ for me and send the output? I might have more insight based on that result.

**Comment by kwglam** [comment]
@a98e7415-5cbe-47cf-8d92-a768895d18bc:TCTGATCC_GTCGTAGA_TTCACGCA_TCTGCGGGTG
ACTTCGTTCAGTTACTACGTGTTGGGTGTTTAGCAAGTTCGCCATACCTACCGTGACAAGAAAGTTGTCGGTGTCTTTGTGTTTCTGTTGGTGCTGATATTGCAAGCAGTGGTATCAACGCAGAGTGAATGGGGCCCCTTCTGCTTGTTATAGCCCCAGTAGTCCTGTCCAGGTTCTGAAAGACTCCACCTACTTTTCCCCAGACTTTCAGCTCTATTCTGGGAGGCATGAAACATCTGCTTTGACAGTGGAGGCAACCAGTAGCATCAGGGAAAAAGTTGTTGAAGATCTCTTTGTAACTTCCACTCCCCAAACTTCCTGAGGATCTCAGAGGTGGAAATGAGAGGTTCCGAGGATGCGGCAGCTGGAACAAGTATTGCAGCGGCTGATCCAGGAACAACTGCGGTATGGCACCCCAACCCGAGAACATGAACTTGCTGGCCATTCAGCACCAGGCCACAGGGAGTGCAGGACCGGCCATCCTACAAACAACTTTTCTTCCACGGAAAACCTCACTCAAGAAGAC

**Comment by fairliereese** [comment]
So this read looks fine to me, but I bet there's some other read buried in your data that's causing the issue, particularly some read with more than 1 or 0 ":" characters in the read name. I just pushed a change that should hopefully fix your issue. As a minimal test for why this should work vs. the previous strategy you can run this Python code:

```python
import pandas as pd
df = pd.DataFrame()
# one read with 1 :, one read with two :s
df['raw_read_name'] = ['@a98e7415-5cbe-47cf-8d92-a768895d18bc:TCTGATCC_GTCGTAGA_TTCACGCA_TCTGCGGGTG', '@a98e7415-5cbe-47cf-8d92:-a768895d18bc:TCTGATCC_GTCGTAGA_TTCACGCA_TCTGCGGGTG']

# this split won't work (original implementation)
df[['read_name', 'bc_umi']] = df['raw_read_name'].str.split(':', expand=True)

# this split will work (new implementation)
 df[['read_name', 'bc_umi']] = df['raw_read_name'].str.rsplit(':', n=1, expand=True)
```

You should be able to clone the latest commits and try out `add_bam_tag.py` again on your same FASTQ. Let me know if it works.

**Comment by kwglam** [comment]
It works great!! Thanks for your help!!
