### ISSUE TITLE
Barcodes from Illumina

### ISSUE THREAD

**Issue by moschmi** [fairliereese/LR-splitpipe#4]
@fairliereese 
this is a great tool! I am using it without much problems. Just 1 question:
I want to filter the Bams by barcodes with the -i_file option.
But the BC output of Parse's Illumina pipeline is not in nucleotides but as numbers for each well in each round eg.: 4-45-62
Is there a database to convert  this "Split-seq demultiplexing code" into nucleotide sequence or vice-versa?
Thanks
Marcel

**Comment by fairliereese** [comment]
Hi there, great question. Below I've included code to format the Illumina barcodes the same way as the long read barcodes:

```python
def get_bc1_matches(bc_fname):
    # from spclass.py - barcodes and their well/primer type identity
    bc_df = pd.read_csv(bc_fname, index_col=0, names=['bc'])
    bc_df['well'] = [i for i in range(0, 48)]+[i for i in range(0, 48)]
    bc_df['primer_type'] = ['dt' for i in range(0, 48)]+['randhex' for i in range(0, 48)]

    # pivot on well to get df that matches bcs with one another from the same well
    bc_df = bc_df.pivot(index='well', columns='primer_type', values='bc')
    bc_df = bc_df.rename_axis(None, axis=1).reset_index()
    bc_df.rename({'dt': 'bc1_dt', 'randhex': 'bc1_randhex'}, axis=1, inplace=True)

    return bc_df

def reformat_illumina_bcs(fname, bc_fname):
  """
    Adds dT primed barcode full 24 nt barcode to Illumina barcodes output
    from short read splitpipe.

    Parameters:
      fname (str): Path to "cell_metadata.csv" file output from splitpipe
      bc_fname (str): Path to "bc_8nt_v2.csv" from the "refs" folder
        of LR-splitpipe

    Returns:
      ill_df (pandas DataFrame): Pandas DataFrame with 24 nt barcode
        added in column "bc"
  """

    # we want info about primer type as well
    bc_df = get_bc1_matches(bc_fname)

    # read in illumina bcs
    ill_df = pd.read_csv(fname)

    # get 24nt barcode
    ill_df = ill_df.merge(bc_df, how='left', \
                 left_on='rnd1_well', right_on='well')

    ill_df['bc3'] = ill_df.cell_barcode.str.slice(start=0, stop=8)
    ill_df['bc2'] = ill_df.cell_barcode.str.slice(start=8, stop=16)
    ill_df['bc1'] = ill_df.bc1_dt
    ill_df['bc'] = ill_df.bc3+ill_df.bc2+ill_df.bc1

    return ill_df
```

This will get you the dataframe you need with the barcodes reported by short read splitpipe into their 24 nt format. 

However it's worth mentioning that I've made some big changes to this repository recently that the current documentation does not reflect. One of these changes is that I haven't re-written the Illumina barcode filtering back in. If you're running an older version of the code, you should be fine! But be wary of updating to the latest commits if you want to use this filter.

**Comment by moschmi** [comment]
Great! Thanks.
