### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by LJK1991** [fairliereese/LR-splitpipe#6]
Hello fairliereese,

I am trying to run your tool on my Data however i get an error as i do so.
The data i use are not long reads but short reads, however i dont think that should stop the pipeline.
When i run this command i get the following error
` python ../LR-splitpipe/demultiplex.py score_linkers -f /media/draco/lucask/LR-splitpipe/myTest/test.fastq -o /media/draco/lucask/LR-splitpipe/myTest/ -t 8 --verbosity 3 --delete_input`

> Traceback (most recent call last):
  File "../LR-splitpipe/demultiplex.py", line 323, in <module>
    if __name__ == '__main__': main()
  File "../LR-splitpipe/demultiplex.py", line 303, in main
    fname = find_bcs(fastq, oprefix, t,
  File "../LR-splitpipe/demultiplex.py", line 109, in find_bcs
    plot_linker_scores(df, oprefix)
  File "/media/draco/lucask/LR-splitpipe/LR-splitpipe/plotting.py", line 26, in plot_linker_scores
    g.map(plot_hist, 'value')
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/seaborn/axisgrid.py", line 710, in map
    self._facet_plot(func, ax, plot_args, kwargs)
  File "/home/lucask/miniconda3/envs/scvelo/lib/python3.8/site-packages/seaborn/axisgrid.py", line 806, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/media/draco/lucask/LR-splitpipe/LR-splitpipe/plotting.py", line 16, in plot_hist
    for l in mismatch_lines:
UnboundLocalError: local variable 'mismatch_lines' referenced before assignment

I am not good enough at Python to fix this issue myself, i have tried putting a Global mismatch_lines in the plot_hist function but that does not fix it. 
I think it has to do with the fact that the if/elif statements in plot_hist dont match to something. 
the pipeline does make the _table.tsv and _seq_linker_alignment_scores.tsv

the test.fastq is a fastq file with 100k reads from my Read2 file. I have noticed in my previous attempts to analyze my data with STARsolo that there is a reasonable amount of reads that have a shift in barcode position due to mismatches in the linkers. I want to test how many reads have a linker and how many have shifts or other mismatches. 
I have also tried @paulranumn11 code with which i get a decent data back, however i would still like to know how many of my reads are of "lower" quality.
your programs seems at glance to do exactly what i want.
I hope you can help.
Thanks in advance.

Regards,
Lucas

**Comment by fairliereese** [comment]
Hi there, 

I just pushed some changes that should solve your problem. Try redownloading the repo and rerunning.

 I am a bit worried about what my code is finding for your linkers though, from how the plotting code I fixed used to work, it looks like there are no perfect linker matches being found in your reads, which seems odd to me. Hopefully you'll be able to further troubleshoot now since the code should actually work 😅

PS I like the cat in your picture!

**Comment by LJK1991** [comment]
Hey
Thank you for the quick reply, I ran the adjusted script and it works fine.
I also, instead of running a tiny subset ran the my whole library and it looks ok.
It also took me a run to figure out that you (your lab) used the commercial SPLiT-seq, my Lab still uses the published protocol. So i had to change the Linker length and sequence of the 1st linker.

One thing i found is that when you adjust the --chunksize argument it doesn't run as it cannot remove the ' ' from the input.
I have tried .strip() or .replace() and even turning it to a float. but for some reason it does not work.

> ValueError: invalid literal for int() with base 10: '10**6'

Additionally, I have a few questions about the plots though.
The HeatMaps show the number of reads found with x mutations in both linkers if am correct.
The numbers though go way beyond my total read count, i only have a 140M total reads.
But maybe i am interpreting it wrong.
![_integer_linker_mismatch_heatmap](https://user-images.githubusercontent.com/16833514/166872358-f1e4bd95-97a7-40d4-a46f-179b35eff5c0.png)

For the distribution it looks fine (i guess, let me know if you agree), but why do you also plot the reverse complement.
unless you are changing how the Read is read on the sequencer it is either one or the other. 
But again maybe i am interpreting it wrongly.
![_linker_score_dists](https://user-images.githubusercontent.com/16833514/166873257-c6b128c0-0531-4fa6-9f8a-1601dfd1711a.png)

Again, thanks for your help so far, it is much appreciated.

PS your cat looks cool too!

**Comment by LJK1991** [comment]
Thank you for your help!
you wrote a nice piece of code.

Regards,
Lucas
