### ISSUE TITLE
"['l2_rc_score'] not in index" error

### ISSUE THREAD

**Issue by kernel32uiuc** [fairliereese/LR-splitpipe#9]
I am getting the following error when running 'score_linkers'. Somehow, l2_rc_score is not calculated, so it does not exist on the map. Any potential cause would be appreciated. 

> [2022-09-04 22:57:03] Found linker scores for 100000 reads
> [2022-09-04 22:58:45] Found linker scores for 200000 reads
> Traceback (most recent call last):
>   File "LR-splitpipe-master/LR-splitpipe/demultiplex.py", line 361, in <module>
>     if __name__ == '__main__': main()
>   File "LR-splitpipe-master/LR-splitpipe/demultiplex.py", line 359, in main
>     delete_input)
>   File "LR-splitpipe-master/LR-splitpipe/demultiplex.py", line 61, in score
>     plot_post_score_plots(df, oprefix)
>   File "LR-splitpipe-master/LR-splitpipe/utils.py", line 173, in plot_post_score_plots
>     plot_linker_scores(df, oprefix)
>   File "LR-splitpipe-master/LR-splitpipe/plotting.py", line 26, in plot_linker_scores
>     temp = df[cols].melt(id_vars='index', value_vars=val_vars)
>   File "opt/miniconda3/envs/mybioconda/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
>     indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
>   File "opt/miniconda3/envs/mybioconda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
>     self._validate_read_indexer(keyarr, indexer, axis)
>   File "opt/miniconda3/envs/mybioconda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
>     raise KeyError(f"{not_found} not in index")
> 
> KeyError: "['l2_rc_score'] not in index"

**Comment by fairliereese** [comment]
Hi there, thanks for pointing out this bug. It's been fixed by the latest commits: [9621c30](https://github.com/fairliereese/LR-splitpipe/commit/9621c3064b977914e4d9f473b0509a6e0174fc8a)

**Comment by kernel32uiuc** [comment]
it works now. Thank you!
